backend:
  name: github
  repo: HushPuppy342/astro-platform-starter
  branch: main

media_folder: "public/images/uploads"
public_folder: "/src/assets"
collections:
  - type: Page
    label: SchoolBundle
    folders:
      - path: "pages"
    media_folder: "src/pages"

