<!-- Note the "type" and "rel" attribute values, which are required. -->
<link href="/admin/config.yml" type="text/yaml" rel="cms-config-url">
backend:
  name: github
  repo: HushPuppy342/astro-platform-starter # Path to your GitHub repository
  # optional, defaults to master
  branch: main
# This line should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads
# These lines should *not* be indented
# media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
# public_folder: "/public/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
public_folder: "/src/assets"
